spring.application.name=Security
server.port=8085

# Configuración de R2DBC para PostgreSQL en Supabase
spring.r2dbc.url=r2dbc:postgresql://db.syyjmpdsuuorxysggtsn.supabase.co:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=andressocalay12

# Configuración de CORS
spring.webflux.cors.allowed-origins=*
spring.webflux.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.webflux.cors.allowed-headers=*

# Configuración de seguridad
security.jwt.secret=clave_secreta_para_jwt_vallegrande_security
security.jwt.expiration=864000000